### ISSUE TITLE
UI Kit Components to make

### ISSUE THREAD

**Issue by alexpricedev** [remotealex/ombits#2]
### V1

- [x] Grid
- [x] Wrapper
- [x] Card
- [x] Navigation
  - [ ] Mobile styles
- [x] Tag
- [x] Image
- [x] Dialog boxes
- [ ] Section (simple coloured bg wrappers)
- [ ] Breadcrumb
- [ ] Inputs (Text, Dropdown, Radio, Select etc.) 

### Pending

- [ ] Notification/Toast

**Comment by gurjit03** [comment]
@remotealex gonna take the tag :)

**Comment by gurjit03** [comment]
@remotealex Taking inputs
